### ISSUE TITLE
move Shogun.app to /Applications automatically

### ISSUE THREAD

**Issue by yusuke** [yusuke/shogun#38]

**Comment by kenchan0130** [comment]
I'm against this policy.
It is up to the user to place the application under the/Applications directory.
For example, if administrative rights are not passed to the logged-in user, or if you want to limit the scope to logged-in users, you often place the application in the $HOME/Applications directory.

I'm sorry if my point is out of the point because I do not know concrete measures.

**Comment by yusuke** [comment]
Got it.
How about the following behavior?
1. check if the user has write permission to /Applications folder
2. if yes, ask user to choose /Applications, $HOME/Applications, or keep the location as is 
3. if no, ask user if they want to move to $HOME/Applications folder
4. the choice will be persisted

**Comment by kenchan0130** [comment]
Rather than the steps you suggested, I would say it is better to have a disc image (dmg) like like google chrome, docker and so on.

**Comment by yusuke** [comment]
got it. I'll just upload dmg containing installer next time
